### ISSUE TITLE
Fastjson 的不恰当使用

### ISSUE THREAD

**Issue by zqq90** [leancloud/java-common#30]
https://github.com/leancloud/java-common/blob/0.1.9/src/main/java/com/avos/avoscloud/AVObject.java#L64

这里改动了 fastjson 的全局设置，这是一个非常大的入侵，在用户不知情的情况下，会给用户带来很大困扰，而且如果用户在不执行的情况下可能会覆盖此设置，引起一些问题
```java
JSON.DEFFAULT_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
```
+ 可以尝试自定义 `Deserializer/Serializer`, 并注册到 **新配置实例** 里面，且一定不能是 `ParserConfig.getGlobalInstance()/SerializeConfig.getGlobalInstance()`，
+ 如果考虑到全局使用，自定义时间类 `AVDate/LCDate` 会更妥当 

PS: 其后的 `AVObjectDeserializer/AVObjectSerializer` 因为处理的我们自定义的 `AVObject` 是比较低的入侵， 并不严重

**Comment by jwfing** [comment]
本项目已经被 java-sdk-all 取代，此 issue 先关闭。
